TimeClock_Core/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using TimeClock_Core.Filters;
using TimeClock_Core.Mapping;
using TimeClock_Core.Models;
using TimeClock_Core_DAL;

namespace TimeClock_Core.Controllers
{
    public class TimeController : Controller
    {
        private readonly TimeEntryDAO timeEntryDataAccess;
        private readonly UserDAO userDataAccess;
        public TimeController(IConfiguration config)
        {
            string connectionString = config.GetValue<string>("DataSource", null);

            timeEntryDataAccess = new TimeEntryDAO(connectionString);
            userDataAccess = new UserDAO(connectionString);
        }

        //[SecurityFilter("/Home/Index", "Role", "Instructor")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        //[SecurityFilter("/Home/Index", "Role", "Instructor")]
        public ActionResult TimeEntries()
        {
            ViewBag.Bootcampers = UserMapper.MapDoToList(userDataAccess.ViewUsers());
            return View();
        }

        [HttpGet]
        [AjaxOnly]
        public ActionResult GetTime(Int64 userId)
        {
            ViewBag.Username = userDataAccess.ViewUserByUserId(userId).Username;
            List<IGrouping<int, TimeEntry>> usersTimes = TimeEntryMapper.MapDoToList(timeEntryDataAccess.ViewByUserId(userId)).GroupBy(x => x.Week).OrderBy(x => x.Key).ToList();

            //List<TimeEntry> usersTimes = new List<TimeEntry>();
            //Times.TryGetValue(username, out usersTimes);
            return PartialView("_UsersTimesTable", usersTimes);
        }
    }
}

TimeClock_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeClock</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />*@
    </environment>
    <environment exclude="Development">
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>

    @* Scripts *@
    <environment include="Development">
        @*<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 
                crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 
                crossorigin="anonymous">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">TimeClock</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    </li>
                </ul>
                <ul class="float-right navbar-nav">
                    <li class="nav-item">
                        <text id="currentTime">@DateTime.Now.ToString("dddd MMM dd, yyyy HH:mm")</text>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - TimeClock</p>
        </footer>
    </div>
    <script>
        $(document).ready(function () {
            var weekdays = new Array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday");
            var months = new Array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
            var interval = setInterval(function () {
                var timeText = $("#currentTime");
                if (timeText) {
                    var now = new Date();
                    timeText.text(weekdays[now.getDay()] + " " + months[now.getMonth()] + " " + now.getDate() + ", " + now.getFullYear() + " " + ("0" + now.getHours()).slice(-2) + ":" + ("0" + now.getMinutes()).slice(-2));
                }
            }, 1000)
        });
    </script>

    @RenderSection("Scripts", required: false)

</body>
</html>

TimeClock_Core/Views/Shared/_TimeManagerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Time Clock</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />*@
    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>

    @* Scripts *@
    <environment include="Development">
        @*<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                crossorigin="anonymous">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            @Html.ActionLink("TimeClock", "Index", "Time", null, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("Time Entries", "TimeEntries", "Time", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active">
                    </li>
                </ul>
                <ul class="float-right navbar-nav">
                    <li class="nav-item">
                        <div class="dropdown">
                            <button id="userNavBtn" class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @*@Session["Username"].ToString()*@
                                Username
                            </button>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @Html.ActionLink("Reports", "Index", "Time", null, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                <h1 class="dropdown-header">Users</h1>
                                @Html.ActionLink("My Class", "Index", "Account", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Create User", "CreateUser", "Account", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Create LMS Users", "ViewLMSGroups", "Account", null, new { @class = "dropdown-item" })
                            </div>
                        </div>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Logout", "Account")">
                            <span class="octicon octicon-sign-out"></span>
                        </a>
                        @*@Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "nav-link" })*@
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

TimeClock_Core/Views/Shared/_UsersTimesTable.cshtml
@model List<IGrouping<int, TimeEntry>>

@if (Model != null && Model.Count() > 0)
{
    foreach (IGrouping<int, TimeEntry> weekEntries in Model)
    {
        <table class="table table-dark">
            @if (Model.IndexOf(weekEntries) == 0)
            {
                <thead>
                    <tr>
                        <th colspan="6">
                            <h3 class="text-center">
                                @ViewBag.Username
                            </h3>
                        </th>
                    </tr>
                    <tr>
                        <th>

                        </th>
                        <th>
                            Date
                        </th>
                        <th>
                            In
                        </th>
                        <th>
                            Out
                        </th>
                        <th>
                            Total
                        </th>
                        <th>
                            <button class="btn btn-sm btn-success">
                                <text>Download</text>
                                <span class="octicon octicon-desktop-download" />
                            </button>
                        </th>
                    </tr>
                </thead>
            }
            @{ TimeSpan total = new TimeSpan();}
            <tbody>
                @foreach (TimeEntry entry in weekEntries)
                {
                    <tr>
                        <td>
                            @entry.TimeIn.DayOfWeek
                        </td>
                        <td>
                            @entry.TimeIn.ToShortDateString()
                        </td>
                        <td>
                            @entry.TimeIn.ToShortTimeString()
                        </td>
                        <td>
                            @if (entry.TimeOut == default(DateTime))
                            {
                                <span class="text-danger">Missing</span>
                            }
                            else
                            {
                                @entry.TimeOut.ToShortTimeString()
                            }
                        </td>
                        <td>
                            @{
                                string displayValue = "";
                                if (entry.TimeOut != default(DateTime))
                                {
                                    TimeSpan ts = entry.TimeOut - entry.TimeIn;
                                    total = total.Add(ts);
                                    displayValue = $"{ts.Hours.ToString("00")}:{ts.Minutes.ToString("00")}";
                                }
                            }
                            @displayValue
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "", "")
                            @Html.ActionLink("Delete", "", "")
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="4"></td>
                    <td>
                        @{ string dv = $"{total.Hours.ToString("00")}:{total.Minutes.ToString("00")}";}
                        @dv
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    }
}
else
{
    <tr>
        <td colspan="5" class="text-center">
            There are no records.
        </td>
    </tr>
}